---
- name: Install Cyberpanel Server
  hosts: cyberpanel
  become: yes
  gather_facts: True
  roles:
    - { role: install-cyberpanel, tags: [cyberpanel] }
    - { role: ntp-config, tags: [ntp] }
    - { role: firewall-config, tags: [firewall] }