---
- name: Download Cyberpanel
  get_url:
    url: https://cyberpanel.net/install.sh
    dest: /tmp/cyberpanel-install.sh
    force: yes
- name: Install Cyberpanel
  shell: bash /tmp/cyberpanel-install.sh -v ols -a -p r
  args:
    chdir: /tmp
  async: 900 #wait for upto 15 minutes
  poll: 120 #check every 2 minutes
  when: cyberpanel_installed is not defined