---
  - name: Update packages
    package:
      name: '*'
      update-cache: True
      state: latest

  - name: Install epel-release on CentOS
    package:
      name: epel-release
    when: ansible_distribution == "Almalinux"

  - name: Install software-properties-common on Ubuntu
    package:
      name: software-properties-common
    when: ansible_distribution == "Ubuntu"

  - name: install other packages after installing epel-release
    package:
      name:
        - htop
        - atop
        - iftop
        - screen
        - wget
      state: present

  - name: Check wheather cyberpanel is installed
    stat:
      path: '/usr/bin/cyberpanel'
    register: cyberpanel_check
    check_mode: no
    failed_when: false
    changed_when: false

  - name: Register cyberpanel_installed variable
    set_fact:
      cyberpanel_installed: ture
    when: cyberpanel_check.stat.exists

  - name: Include the Cyberpanel Installer Task
    include_tasks: install.yaml
    when: cyberpanel_installed is not defined