---
  - name: Updating the server (dnf update)
    dnf:
      name: '*'
      state: latest
  - name: Install pre-requisit for other packages
    dnf:
      name:
        - epel-release
  - name: install other packages after installing epel-release
    dnf:
      name:
        - htop
        - atop
        - iftop
        - screen
        - wget
      state: present
  - name: Include the Cyberpanel Installer Task
    include_tasks: install.yml

