---
  - name: Start and enable firewalld
    service:
      name: firewalld
      state: started
      enabled: yes
  - name: allow ntp through firewall
    shell: firewall-cmd --add-service=ntp --permanent
  - name: firewall reload
    shell: firewall-cmd --reload